[project]
name = "loading-py"
version = "0.1.0"
description = "Ex1, python Module 8"
authors = [
    {name = "RruizVM",email = "rz.remy@outlook.fr"}
]
requires-python = ">=3.11"
dependencies = [
    "pandas (>=3.0.0,<4.0.0)",
    "requests (>=2.32.5,<3.0.0)",
    "matplotlib (>=3.10.8,<4.0.0)"
]

[tool.poetry]
packages = [{include = "loading"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

